name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Check Python version
      run: python --version  # This will display the Python version to confirm it's 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install webdriver-manager  # Install webdriver-manager to handle chromedriver automatically

    - name: Set up ChromeDriver permissions
      run: |
        chmod +x ./tests/chromedriver  # Ensure chromedriver is executable

    - name: Run the app in the background
      run: |
        # Run the application in the background (replace with the command that starts your app)
        nohup python src/app.py &  

    - name: Wait for the app to be ready
      run: |
        # Wait a few seconds for the app to fully start
        sleep 5  # Adjust the time depending on how long your app needs to start

    - name: Run tests
      run: |
        pytest
